//Usuario
export const USUARIO_LOGIN = "USUARIO_LOGIN";
export const USUARIO_CERRAR_SESION = "USUARIO_CERRAR_SESION";
export const USUARIO_INSCRIPCIONES_SET = 'USUARIO_INSCRIPCIONES_SET';

//GESTION
export const GESTION_EVENTOS_SET = "GESTION_EVENTOS_SET";
export const GESTION_EVENTOS_INIT = "GESTION_EVENTOS_INIT";

//Eventos
export const EVENTOS_SET = "EVENTOS_SET";
export const EVENTOS_INIT = "EVENTOS_INIT";
export const EVENTOS_GANADORES_SET = 'EVENTOS_GANADORES_SET';
export const EVENTOS_MENSAJES_SET = 'EVENTOS_MENSAJES_SET';

//Evento
export const EVENTO_SET = "EVENTO_SET";
export const EVENTO_GANADORES_SET = 'EVENTO_GANADORES_SET';
export const EVENTO_MENSAJES_SET = 'EVENTO_MENSAJES_SET';
